name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASS }}

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.USER }}/vote ./vote
          docker push ${{ secrets.USER }}/vote

          docker build -t ${{ secrets.USER }}/result ./result
          docker push ${{ secrets.USER }}/result

          docker build -t ${{ secrets.USER }}/worker ./worker
          docker push ${{ secrets.USER }}/worker

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install app ./infrastructure