name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

      - name: Install Okteto
        run: curl https://get.okteto.com -sSfL | sh

      - name: Okteto Login
        run: okteto login --token ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy to Okteto
        run: okteto deploy