name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Okteto CLI
        run: |
          curl -L https://github.com/okteto/okteto/releases/latest/download/okteto-Linux-x86_64 -o okteto
          chmod +x okteto
          sudo mv okteto /usr/local/bin/okteto

      - name: Deploy to Okteto
        run: okteto deploy