name: CI

on:
  push:
    branches: [dev, feature/*]
  pull_request:
    branches: [dev]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      # VOTE
      - name: Build Vote (Maven)
        run: |
          cd vote
          mvn clean package

      # RESULT
      - name: Install Result deps
        run: |
          cd result
          npm install

      # WORKER (FIXED)
      - name: Build Worker
        run: |
          cd worker
          go mod download
          go build -o app ./...

      # DOCKER
      - name: Build Docker images
        run: |
          docker build -t vote ./vote
          docker build -t result ./result
          docker build -t worker ./worker